workflows:
  android-workflow:
    name: Build Android Natif & Publier sur le Play Store
    environment:
      groups:
        - play_console_credentials
        - keystore_credentials
      vars:
        PACKAGE_NAME: "dcmchonorable.iwt"
    scripts:
      # --- Étape 1 : Décoder le keystore de signature ---
      - name: Décoder le keystore de signature
        script: |
          echo $CM_KEYSTORE | base64 --decode > app/keystore.jks
          echo "Keystore décodé avec succès."

      # --- Étape 2 : Créer le fichier key.properties ---
      - name: Créer le fichier key.properties
        script: |
          cat > app/key.properties <<EOL
          storeFile=keystore.jks
          storePassword=$CM_KEYSTORE_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          keyPassword=$CM_KEY_PASSWORD
          EOL
          echo "Fichier key.properties créé."

      # --- Étape 3 : Construire avec Gradle 8.14.1 ---
      - name: Build Android App Bundle (AAB)
        script: |
          ./gradlew bundleRelease --no-daemon --warning-mode=all
          echo "Build AAB terminé."

    artifacts:
      - app/build/outputs/bundle/release/**/*.aab

    publishing:
      email:
        recipients:
          - votre.email@exemple.com
      google_play:
        credentials: $PLAY_STORE_CREDENTIALS
        track: internal
