# Configuration Codemagic pour Android (Flutter) - CORRIGÉ
workflows:
  android-workflow:
    name: Build Android & Publier sur le Play Store
    environment:
      groups:
        - play_console_credentials # Groupe contenant les credentials Google Play (fichier JSON)
        - keystore_credentials # Groupe contenant le keystore et ses mots de passe
      vars:
        PACKAGE_NAME: "dcmchonorable.iwt" # REMPLACEZ par votre ID d'application
    scripts:
      # --- Étape 1 : Décoder le keystore ---
      - name: Décoder le keystore de signature
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/keystore.jks
          echo "Keystore décodé avec succès."

      # --- Étape 2 : Construire l'Android App Bundle (AAB) signé ---
      - name: Build Android App Bundle (AAB)
        script: |
          flutter build appbundle --release \
            --target-platform android-arm,android-arm64,android-x64 \
            --keystore="$CM_BUILD_DIR/keystore.jks" \
            --store-password="$CM_KEYSTORE_PASSWORD" \
            --key-alias="$CM_KEY_ALIAS" \
            --key-password="$CM_KEY_PASSWORD"
          echo "Build AAB terminé."

    artifacts:
      - build/app/outputs/bundle/release/**/*.aab # Chemin vers le AAB généré

    publishing:
      email:
        recipients:
          - votre.email@exemple.com # REMPLACEZ par votre email pour les notifications
      # --- SECTION CORRIGÉE : Utiliser google_play au lieu de app_store_connect ---
      google_play: # <- CORRECTION ICI. C'est pour GOOGLE.
        credentials: $PLAY_STORE_CREDENTIALS # Référence à la variable contenant le JSON Google
        track: internal # Piste de déploiement : internal, alpha, beta, production
        # in_progress: true # Déploie en "version draft" (brouillon)
        # submit_to_review: false # NE PAS soumettre automatiquement en review
