# Configuration Codemagic pour Android Natif
workflows:
  android-workflow:
    name: Build Android Natif & Publier sur le Play Store
    environment:
      groups:
        - play_console_credentials
        - keystore_credentials
      vars:
        PACKAGE_NAME: "dcmchonorable.iwt"
    scripts:
      # --- Étape de diagnostic ---
      - name: Diagnostiquer la structure du projet
        script: |
          echo "Structure du projet :"
          ls -la
          echo ""
          echo "Fichiers build.gradle :"
          find . -name "build.gradle" -exec echo {} \;
          echo ""
          echo "Recherche de gradle wrapper :"
          find . -name "gradle-wrapper.properties" -exec cat {} \;

      # --- Étape 1 : Décoder le keystore de signature ---
      - name: Décoder le keystore de signature
        script: |
          echo $CM_KEYSTORE | base64 --decode > app/keystore.jks
          echo "Keystore décodé avec succès."

      # --- Étape 2 : Créer le fichier key.properties ---
      - name: Créer le fichier key.properties
        script: |
          cat > app/key.properties <<EOL
storeFile=keystore.jks
storePassword=$CM_KEYSTORE_PASSWORD
keyAlias=$CM_KEY_ALIAS
keyPassword=$CM_KEY_PASSWORD
EOL
          echo "Fichier key.properties créé."

      # --- Étape 3 : Utiliser Gradle système ---
      - name: Utiliser Gradle système
        script: |
          # Essayer de trouver gradlew ou utiliser gradle du système
          if [ -f "gradlew" ]; then
              echo "Utilisation du gradlew existant"
              chmod +x gradlew
              ./gradlew bundleRelease --no-daemon --warning-mode=none
          elif command -v gradle >/dev/null 2>&1; then
              echo "Utilisation de gradle du système"
              gradle bundleRelease --no-daemon --warning-mode=none
          else
              echo "Gradle non trouvé, tentative d'installation..."
              # Méthodes alternatives pour exécuter Gradle
              if [ -f "android/gradlew" ]; then
                  cd android
                  chmod +x gradlew
                  ./gradlew bundleRelease --no-daemon --warning-mode=none
              else
                  echo "ERREUR: Gradle non disponible"
                  exit 1
              fi
          fi
          echo "Build AAB terminé."

    artifacts:
      - app/build/outputs/bundle/release/**/*.aab

    publishing:
      email:
        recipients:
          - votre.email@exemple.com
      google_play:
        credentials: $PLAY_STORE_CREDENTIALS
        track: internal
