workflows:
  android-workflow:
    name: Build Android Natif & Publier sur le Play Store
    environment:
      groups:
        - play_console_credentials
        - keystore_credentials
      vars:
        PACKAGE_NAME: "dcmchonorable.iwt"
    scripts:
      # --- Étape 1 : Vérifier la structure ---
      - name: Vérifier la structure
        script: |
          echo "Structure du projet :"
          ls -la
          echo ""
          echo "Dossier app existe ? :"
          ls -la app/ || echo "Dossier app non trouvé"

      # --- Étape 2 : Configurer AndroidX ---
      - name: Configurer AndroidX
        script: |
          cat > gradle.properties <<EOL
          android.useAndroidX=true
          android.enableJetifier=true
          org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
          EOL
          echo "Fichier gradle.properties créé pour AndroidX"

      # --- Étape 3 : Générer le Gradle Wrapper ---
      - name: Générer le Gradle Wrapper
        script: |
          gradle wrapper --gradle-version 8.14.1 --distribution-type bin
          chmod +x ./gradlew
          echo "Gradle Wrapper généré"

      # --- Étape 4 : Décoder le keystore ---
      - name: Décoder le keystore de signature
        script: |
          echo $CM_KEYSTORE | base64 --decode > keystore.jks
          echo "Keystore décodé avec succès."
          ls -la keystore.jks || echo "Keystore non créé"

      # --- Étape 5 : Créer key.properties ---
      - name: Créer le fichier key.properties
        script: |
          cat > key.properties <<EOL
          storeFile=keystore.jks
          storePassword=$CM_KEYSTORE_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          keyPassword=$CM_KEY_PASSWORD
          EOL
          echo "Fichier key.properties créé."
          cat key.properties

      # --- Étape 6 : Build AAB ---
      - name: Build Android App Bundle (AAB)
        script: |
          ./gradlew bundleRelease --no-daemon --warning-mode=none
          echo "Build AAB terminé."

    artifacts:
      - app/build/outputs/bundle/release/**/*.aab

    publishing:
      email:
        recipients:
          - votre.email@exemple.com
      google_play:
        credentials: $PLAY_STORE_CREDENTIALS
        track: internal
