# Configuration Codemagic pour Android (Flutter)
# Ce fichier doit être placé à la racine de votre dépôt Git.
workflows:
  android-workflow:
    name: Build Andoid & Publier sur le Play Store
    environment:
      groups:
        - play_console_credentials # Groupe contenant les credentials Google Play (fichier JSON)
        - keystore_credentials # Groupe contenant le keystore et ses mots de passe
      vars:
        PACKAGE_NAME: "com.votrecompagnie.votreapp" # REMPLACEZ par votre ID d'application
        BUNDLE_NAME: "app-release" # Nom base du fichier de sortie
    scripts:
      # --- Étape 1 : Décoder le keystore ---
      - name: Décoder le keystore de signature
        script: |
          # Décode la variable CM_KEYSTORE (en Base64) pour recréer le fichier keystore.jks
          echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/keystore.jks
          echo "Keystore décodé avec succès."

      # --- Étape 2 : Construire l'Android App Bundle (AAB) signé ---
      - name: Build Android App Bundle (AAB)
        script: |
          # Build Flutter en mode release avec les paramètres de signature
          flutter build appbundle --release \
            --target-platform android-arm,android-arm64,android-x64 \
            --build-name=1.0.0 \ # Optionnel : Définit le versionName
            --build-number=1 \ # Optionnel : Incrémente le versionCode
            --keystore="$CM_BUILD_DIR/keystore.jks" \
            --store-password="$CM_KEYSTORE_PASSWORD" \
            --key-alias="$CM_KEY_ALIAS" \
            --key-password="$CM_KEY_PASSWORD"
          echo "Build AAB terminé."

      # --- (Optionnel) Construire un APK universel signé ---
      # - name: Build APK Universel
      #   script: |
      #     flutter build apk --release \
      #       --target-platform android-arm,android-arm64,android-x64 \
      #       --keystore="$CM_BUILD_DIR/keystore.jks" \
      #       --store-password="$CM_KEYSTORE_PASSWORD" \
      #       --key-alias="$CM_KEY_ALIAS" \
      #       --key-password="$CM_KEY_PASSWORD"
      #     echo "Build APK terminé."

    artifacts:
      - build/app/outputs/bundle/release/**/*.aab # Chemin vers le AAB généré
      # - build/app/outputs/apk/release/**/*.apk # Décommentez si vous builduez un APK

    publishing:
      email:
        recipients:
          - votre.email@exemple.com # REMPLACEZ par votre email pour les notifications
      app_store_connect: # Publication sur Google Play
        credentials: $PLAY_STORE_CREDENTIALS # Référence à la variable contenant le JSON
        track: internal # Piste de déploiement : internal, alpha, beta, production
        # in_progress: true # Déploie en "version draft" (brouillon)
        # submit_to_review: false # NE PAS soumettre automatiquement en review pour production
        # changes_not_sent_for_review: true # Pour les tracks qui ne nécessitent pas de review (internal)
        
